- name: configure web server
  hosts: all
  tasks:
  - name: install package
    yum:
     name: httpd
     state: present
  - name: copy website
    copy:
     content: "Hello World Samuel"
     dest: /var/www/html/index.html
  - name: restart service
    service:
     name: httpd
     state: restarted
     enabled: true
  - name: create user
    user:
     name: samuel
     state: present
